import "./styles.css";
import { tools, toolById } from "./tools.js";
import { runTool } from "./engine.js";
import { t } from "./i18n.js";
import { APP_CONFIG } from "./config.js";

const root=document.querySelector("#app");
const cats=["formatter","validator","converter","crypto","minifier","string","resource"];
const state={lang:localStorage.getItem("ff-lang")||"en",theme:localStorage.getItem("ff-theme")||"dark",query:"",category:"all",input:"",output:"",outputType:"text",validation:null,options:{},mobileMenu:false};
document.documentElement.dataset.theme=state.theme;
const safe=(s="")=>String(s).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const display=b=>b?.[state.lang]??b?.en??"";
const route=()=>location.hash.replace(/^#\/?/,"")||"home";
const adSlot=(name)=>APP_CONFIG.ads.enabled?`<aside class="ad-slot" data-ad-slot="${name}"><span>${t(state.lang,"advertisement")}</span><strong>${t(state.lang,"sponsored")}</strong><small>${name}</small></aside>`:"";
const filteredTools=()=>{const q=state.query.toLowerCase().trim();return tools.filter(x=>(state.category==="all"||x.category===state.category)&&(`${x.name.en} ${x.name.id} ${x.desc.en} ${x.desc.id} ${x.id}`.toLowerCase().includes(q)))};

function header(){return `<header class="topbar"><button class="menu-button" data-action="menu" aria-label="Open navigation" aria-expanded="${state.mobileMenu}"><span></span><span></span><span></span></button><a href="#" class="logo"><span class="ff-mark">FF</span><strong>FormatterFree</strong></a><nav><a href="#about">${t(state.lang,"pages.about")}</a><a href="#privacy">${t(state.lang,"pages.privacy")}</a><a href="#terms">${t(state.lang,"pages.terms")}</a><a href="#contact">${t(state.lang,"pages.contact")}</a></nav><div class="actions"><button data-action="lang">${state.lang.toUpperCase()}</button><button data-action="theme">${state.theme==="dark"?"☀":"☾"}</button></div></header>`}
function sidebar(mobile=false){return `<aside class="sidebar ${mobile?`mobile-sidebar ${state.mobileMenu?"open":""}`:"desktop-sidebar"}"><div class="mobile-sidebar-head">${mobile?`<button class="drawer-close" data-action="menu-close" aria-label="Close navigation">×</button>`:""}</div><a href="#" class="side-logo"><span class="ff-mark">FF</span><div><strong>FormatterFree</strong><small>${tools.length} tools</small></div></a><button class="search-jump" data-action="focus-search">⌕ ${t(state.lang,"search")}</button><nav class="cats"><button data-cat="all" class="${state.category==="all"?"active":""}">${t(state.lang,"allTools")}<b>${tools.length}</b></button>${cats.map(c=>`<button data-cat="${c}" class="${state.category===c?"active":""}">${t(state.lang,`categories.${c}`)}<b>${tools.filter(x=>x.category===c).length}</b></button>`).join("")}</nav><nav class="mobile-info-links"><a href="#about">${t(state.lang,"pages.about")}</a><a href="#privacy">${t(state.lang,"pages.privacy")}</a><a href="#terms">${t(state.lang,"pages.terms")}</a><a href="#contact">${t(state.lang,"pages.contact")}</a></nav><div class="side-local"><span></span><div><strong>${t(state.lang,"local")}</strong><small>${t(state.lang,"localDesc")}</small></div></div></aside>`}
function footer(){return `<footer><strong>FormatterFree</strong><span>${t(state.lang,"footerNote")}</span><nav><a href="#about">${t(state.lang,"pages.about")}</a><a href="#privacy">${t(state.lang,"pages.privacy")}</a><a href="#terms">${t(state.lang,"pages.terms")}</a><a href="#contact">${t(state.lang,"pages.contact")}</a></nav></footer>`}
function card(tool){return `<article class="tool-card" data-tool="${tool.id}"><span>${tool.category}</span><h3>${safe(display(tool.name))}</h3><p>${safe(display(tool.desc))}</p><b>Open →</b></article>`}
function home(){const list=filteredTools();return `<main class="content"><section class="hero"><span class="pill">${t(state.lang,"local")}</span><h1>${t(state.lang,"heroTitle")}</h1><p>${t(state.lang,"heroDesc")}</p><div class="hero-search"><input id="search" value="${safe(state.query)}" placeholder="${t(state.lang,"searchHint")}" autocomplete="off" inputmode="search"/></div></section>${adSlot("home-top")}<section><div class="section-head"><h2>${state.category==="all"?t(state.lang,"allTools"):t(state.lang,`categories.${state.category}`)}</h2><span data-search-count>${list.length}</span></div><div class="tool-grid" data-search-results>${list.map(card).join("")||`<div class="empty">${t(state.lang,"noResult")}</div>`}</div></section>${adSlot("home-bottom")}${footer()}</main>`}
function updateSearchResults(){const list=filteredTools();const grid=root.querySelector("[data-search-results]");const count=root.querySelector("[data-search-count]");if(grid)grid.innerHTML=list.map(card).join("")||`<div class="empty">${t(state.lang,"noResult")}</div>`;if(count)count.textContent=String(list.length)}
function optionControl(o){const v=state.options[o.key]??o.default??"";if(o.type==="select")return `<label><span>${display(o.label)}</span><select data-option="${o.key}">${o.values.map(x=>`<option ${x===v?"selected":""}>${x}</option>`).join("")}</select></label>`;if(o.type==="textarea")return `<label class="wide"><span>${display(o.label)}</span><textarea data-option="${o.key}">${safe(v)}</textarea></label>`;return `<label><span>${display(o.label)}</span><input data-option="${o.key}" type="${o.type==="number"?"number":"text"}" value="${safe(v)}"/></label>`}
function toolPage(id){const tool=toolById(id);if(!tool)return home();if(state.input==="")state.input=tool.sample||"";if(!Object.keys(state.options).length)state.options=Object.fromEntries((tool.options||[]).map(o=>[o.key,o.default??""]));return `<main class="content"><div class="tool-head"><a href="#">← ${t(state.lang,"allTools")}</a><span>${t(state.lang,`categories.${tool.category}`)}</span><h1>${display(tool.name)}</h1><p>${display(tool.desc)}</p></div>${adSlot("tool-top")}${tool.options?.length?`<section class="options">${tool.options.map(optionControl).join("")}</section>`:""}<section class="workspace"><div class="editor"><header><strong>${t(state.lang,"input")}</strong><div><button data-action="sample">${t(state.lang,"sample")}</button><button data-action="clear">${t(state.lang,"clear")}</button></div></header><textarea id="input">${safe(state.input)}</textarea></div><button class="run" data-action="run">→<small>${t(state.lang,"run")}</small></button><div class="editor"><header><strong>${t(state.lang,"output")}</strong><div><button data-action="copy">${t(state.lang,"copy")}</button><button data-action="download">${t(state.lang,"download")}</button></div></header>${state.outputType==="image"&&state.output?`<div class="image-output"><img src="${state.output}" alt="Generated output"/></div>`:`<textarea readonly>${safe(state.output)}</textarea>`}</div></section>${adSlot("tool-bottom")}${footer()}</main>`}
function infoPage(name){const map={about:["aboutTitle","aboutBody"],privacy:["privacyTitle","privacyBody"],terms:["termsTitle","termsBody"],contact:["contactTitle","contactBody"]};const [title,body]=map[name];return `<main class="content info-page"><a href="#">← ${t(state.lang,"allTools")}</a><h1>${t(state.lang,title)}</h1><p>${t(state.lang,body)}</p>${name==="contact"?`<div class="contact-card"><strong>GitHub</strong><a href="https://github.com/esarijal/formatterfree" target="_blank" rel="noreferrer">github.com/esarijal/formatterfree</a></div>`:""}${name==="privacy"?`<h2>Advertising and third-party services</h2><p>FormatterFree contains reserved placements that may be used for advertising, affiliate links, or sponsors. When a third-party service is activated, this policy will be updated to describe the provider and relevant data handling.</p>`:""}${footer()}</main>`}
function render(){const r=route();const body=r.startsWith("tool/")?toolPage(r.split("/")[1]):["about","privacy","terms","contact"].includes(r)?infoPage(r):home();root.innerHTML=`<div class="app">${sidebar()}<section class="main">${header()}${body}</section></div><div class="drawer-backdrop ${state.mobileMenu?"open":""}" data-action="menu-close"></div>${sidebar(true)}`;document.body.classList.toggle("drawer-open",state.mobileMenu)}
function resetTool(id){const tool=toolById(id);state.input=tool?.sample||"";state.output="";state.validation=null;state.outputType="text";state.options=Object.fromEntries((tool?.options||[]).map(o=>[o.key,o.default??""]));}
async function execute(){const id=route().split("/")[1],tool=toolById(id);if(!tool)return;state.input=document.querySelector("#input")?.value??state.input;document.querySelectorAll("[data-option]").forEach(el=>state.options[el.dataset.option]=el.value);const r=await runTool(tool,state.input,state.options);state.output=r.output||"";state.outputType=r.outputType||tool.outputType||"text";state.validation=r.validation||null;render()}
root.addEventListener("input",e=>{if(e.target.id==="search"){state.query=e.target.value;updateSearchResults();return}if(e.target.id==="input")state.input=e.target.value;if(e.target.matches("[data-option]"))state.options[e.target.dataset.option]=e.target.value});
root.addEventListener("click",e=>{const c=e.target.closest("[data-cat]");if(c){state.category=c.dataset.cat;state.mobileMenu=false;location.hash="";render();return}const tc=e.target.closest("[data-tool]");if(tc){state.mobileMenu=false;resetTool(tc.dataset.tool);location.hash=`tool/${tc.dataset.tool}`;return}const a=e.target.closest("[data-action]")?.dataset.action;if(a==="menu"){state.mobileMenu=!state.mobileMenu;render()}if(a==="menu-close"){state.mobileMenu=false;render()}if(a==="lang"){state.lang=state.lang==="en"?"id":"en";localStorage.setItem("ff-lang",state.lang);render()}if(a==="theme"){state.theme=state.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=state.theme;localStorage.setItem("ff-theme",state.theme);render()}if(a==="focus-search"){state.mobileMenu=false;location.hash="";render();requestAnimationFrame(()=>document.querySelector("#search")?.focus())}if(a==="run")execute();if(a==="clear"){state.input="";state.output="";render()}if(a==="sample"){resetTool(route().split("/")[1]);render()}if(a==="copy"&&state.output)navigator.clipboard.writeText(state.output);if(a==="download"&&state.output){const blob=new Blob([state.output],{type:"text/plain"}),url=URL.createObjectURL(blob),x=document.createElement("a");x.href=url;x.download="formatterfree-output.txt";x.click();URL.revokeObjectURL(url)}});
window.addEventListener("hashchange",()=>{state.mobileMenu=false;if(route().startsWith("tool/"))resetTool(route().split("/")[1]);render()});
window.addEventListener("keydown",e=>{if(e.key==="Escape"&&state.mobileMenu){state.mobileMenu=false;render()}});
render();
